ministryofjustice/hmpps-incident-reporting-api

docs/0001-use-adr.md
docs/0002-architecture.md
docs/0003-migration.md
docs/9999-end.md

Three new documentation files have been added - "0002-architecture.md", "0003-migration.md", and "9999-end.md". They detail the proposed architecture for an Incident Reporting System and the procedure for data migration, respectively. Additionally, navigation links have been inserted into "0001-use-adr.md" to guide the reader through the documentation.

IR-120 Add new documentation for architecture and data migration

---

src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/dto/CreateIncidentReportRequest.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/dto/IncidentReport.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/jpa/IncidentEvent.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/jpa/IncidentReport.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/jpa/repository/IncidentEventRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/model/nomis/NomisIncidentReport.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/resource/ApiExceptionHandler.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/service/IncidentReportService.kt
src/main/resources/db/migration/V1_3__events.sql
src/test/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/helper/IncidentReportBuilder.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/jpa/IncidentReportReportRepositoryTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/resource/IncidentReportResourceTest.kt

An incident can be linked to an event and an event can have multiple incidents

IR-183 Add the concept of an event to the incident report.

---

docs/0004-modeling-irs.md
src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/dto/HistoricalQuestion.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/dto/Question.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/jpa/HistoricalQuestion.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/jpa/History.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/jpa/Question.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/jpa/Report.kt
src/main/resources/db/migration/V1_1__initial_schema.sql
src/test/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/resource/NomisSyncResourceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/service/SyncServiceTest.kt

• require all questions to have a non-null human readable description (NOMIS models already do this)
• include “additional information” field on questions throughout that was already present in database tables
• normalise varchar column sizes – constants/enumeration keys can all be 60 in length

IR-196: Database tweaks

---

src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/dto/request/NomisSyncRequest.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/dto/response/ConstantDescription.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/dto/response/DeactivatableConstantDescription.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/service/ReportService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/service/SyncService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/integration/IntegrationTestBase.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/integration/SqsIntegrationTestBase.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/resource/NomisSyncResourceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/service/SyncServiceTest.kt
src/test/resources/nomis-sync/sample-report.json

… and disallow updating reports during initial migration

IR-195: Improve testing of sync requests from NOMIS

---

src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/constants/StaffRole.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/dto/NomisDtoToJpaMappingEdgeCaseTest.kt

IR-199: Test NOMIS→Entity→DPS mappings

---

applicationinsights.dev.json
applicationinsights.json

Taken from upstream [hmpps-template-typescript#204](https://github.com/ministryofjustice/hmpps-template-kotlin/pull/204/files?w=1#diff-db66e89c8686cdef7ed55c44cd6b14e0052868ba481585d371f2d5b78c082521)

IR-68: Update Application Insights sampling settings

---

README.md

Instructions on how to use `portForwardRDS`/`portForwardRedis` gradle tasks
Copied from Non-associations API.

README: Instructions to connect to DB/Redis

---

src/main/resources/db/migration/V1_1__initial_schema.sql

IR-247: Add more potentially-useful database indices

---

src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/resource/ApiExceptionHandler.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/resource/NomisSyncResource.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/service/NomisSyncService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/service/SyncService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/resource/NomisSyncResourceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/service/NomisSyncServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/service/SyncServiceTest.kt

Return 409 CONFLICT if initial migration retries a report that has already been created.

IR-260: NOMIS initial migration conflict

---

src/main/resources/db/migration/V1_1__initial_schema.sql

…so that dropping the tables or columns cascades dropping the sequence

IR-68: Have database sequences be owned by tables

---

src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/service/PrisonOffenderEventListener.kt
src/main/resources/application-localstack.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/service/PrisonerMergeTest.kt
src/test/resources/application-test.yml

… and replace prisoner involvements referring to old prisoner number.
Depends on:
- [cp-26514](https://github.com/ministryofjustice/cloud-platform-environments/pull/26514)
- [cp-26515](https://github.com/ministryofjustice/cloud-platform-environments/pull/26515)
- [cp-26516](https://github.com/ministryofjustice/cloud-platform-environments/pull/26516)

IR-512: Listen out for prisoner booking moves

---

src/main/resources/db/seed/R__01_docker_seed.sql

Depends on:
- [nomis-user-roles-api#303](https://github.com/ministryofjustice/nomis-user-roles-api/pull/303)
- [hmpps-auth#1811](https://github.com/ministryofjustice/hmpps-auth/pull/1811)

IR-573: Update DB seed with new test users

---

src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/constants/Type.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/resource/ReportResourceTest.kt

See: https://mojdt.slack.com/archives/C060K95M5MJ/p1731322757968019

DAMAGE was deactivated in NOMIS

---

src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/jpa/HistoricalQuestion.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/jpa/History.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/jpa/Question.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/jpa/Report.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/service/ReportService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/helper/ReportBuilder.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/resource/NomisSyncResourceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/service/NomisSyncServiceTest.kt
src/test/resources/entity-mapping/sample-report-with-details.json
src/test/resources/questions-with-responses/add-and-update-response-with-responses.json
src/test/resources/questions-with-responses/add-response-3-questions-with-responses.json
src/test/resources/questions-with-responses/add-response-with-responses-and-null-fields.json
src/test/resources/questions-with-responses/add-response-with-responses.json
src/test/resources/questions-with-responses/add-response-without-responses.json
src/test/resources/questions-with-responses/delete-response.json
src/test/resources/questions-with-responses/list-response-with-several.json
src/test/resources/questions-with-responses/update-response-with-responses.json

- INCIDENT_CASE_PARTIES
- INCIDENT_CASE_REQUIREMENTS
- INCIDENT_CASE_RESPONSES
All start at sequence 0
- INCIDENT_CASE_QUESTIONS
Starts at sequence 1

IR-723 Correct sequences to match NOMIS

---

src/test/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/config/LocalStackContainer.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/config/PostgresContainer.kt

…and make testcontainer classes more alike

IR-68: Specify postgres testcontainer version/tag

---

helm_deploy/values-preprod.yaml

Equivalent of 2cdf4c92ddc17507b322eddb94f8aca6a477ddf6 from #217

IR-683: Reduce sampling temporarily in `preprod` for NOMIS migration

---

helm_deploy/values-prod.yaml

Equivalent of 2cdf4c92ddc17507b322eddb94f8aca6a477ddf6 from #217

IR-683: Reduce sampling temporarily in `prod` for NOMIS migration

---

helm_deploy/values-prod.yaml

Undoes #244
PR trio:
- [dev](/ministryofjustice/hmpps-incident-reporting-api/pull/219)
- [preprod](/ministryofjustice/hmpps-incident-reporting-api/pull/252)
- [prod](/ministryofjustice/hmpps-incident-reporting-api/pull/253)

IR-683: Revert temporary sampling change in `prod` for NOMIS migration

---

helm_deploy/values-preprod.yaml

Undoes #243
PR trio:
- [dev](/ministryofjustice/hmpps-incident-reporting-api/pull/219)
- [preprod](/ministryofjustice/hmpps-incident-reporting-api/pull/252)
- [prod](/ministryofjustice/hmpps-incident-reporting-api/pull/253)

IR-683: Revert temporary sampling change in `preprod` for NOMIS migration

---

helm_deploy/values-dev.yaml

Undoes commit 2cdf4c92ddc17507b322eddb94f8aca6a477ddf6 from #217
PR trio:
- [dev](/ministryofjustice/hmpps-incident-reporting-api/pull/219)
- [preprod](/ministryofjustice/hmpps-incident-reporting-api/pull/252)
- [prod](/ministryofjustice/hmpps-incident-reporting-api/pull/253)

IR-683: Revert temporary sampling change in `dev` for NOMIS migration

---

build.gradle.kts
src/main/resources/application.yml
src/main/resources/reports/incident-count.json
src/main/resources/reports/incident-report-pecs.json
src/test/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/resource/DprReportingIntegrationTest.kt

- Add a sample PECS reports and control access by a PECS role 
- Allow link to individual incident reports from summary counts of reports
- Upgrade DPR lib

IR-949 Add a sample PECS reports and control access by a PECS role

---

src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/constants/TypeFamily.kt
src/main/resources/db/migration/V1_17__type_description.sql

Related [ui#415](https://github.com/ministryofjustice/hmpps-incident-reporting/pull/415)

IR-785: Simplify damage incident type description

---

src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/dto/nomis/NomisReport.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/dto/request/DescriptionAddendumRequest.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/jpa/DescriptionAddendum.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/jpa/Report.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/resource/ReportResource.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/service/ReportService.kt
src/main/resources/db/migration/V1_20__add_sequence_to_description_addendum.sql
src/test/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/dto/GetDescriptionPartsTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/resource/NomisSyncResourceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/resource/ReportResourceTest.kt

This Pull Request introduces a new sequence field to the DescriptionAddendum entity, which is used to order addendums in incident reports. The changes also include updates to handle this new field in database schemas, DTOs, services, resources, and tests.
- Added a new sequence field to the DescriptionAddendum entity, DTOs, and database schema for ordering purposes.
- Updated methods across services and repositories to populate and use the sequence field.
- Introduced a new DescriptionAddendumRequest DTO to handle addendum creation through API endpoints.
- Updated sorting logic in the DescriptionAddendum entity to use the sequence field.
- Modified existing tests and added cases to validate the use of the sequence field.
- Updated database migrations to reflect the addition of the …

IR-1000 Add sequence tracking to description addendums

---

src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/dto/nomis/NomisReport.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/dto/GetDescriptionPartsTest.kt

This Pull Request refactors the NomisReport class to improve exception handling and logging when parsing incident description data. It also updates related tests to align with the modified behaviour.
- Added logging capability to NomisReport for better error tracking during validation failures.
- Modified the getDescriptionParts() method to handle exceptions gracefully and return a default value instead of throwing them.
- Split complex logic into helper methods (buildAddendum) for improved clarity and maintainability.
- Updated test cases in GetDescriptionPartsTest to remove validations expecting exceptions and verify the new expected return behaviour.

IR-1002 Handle validation gracefully in NomisReport description parsing.

---

src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/dto/nomis/NomisReport.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/dto/GetDescriptionPartsTest.kt

Refined date parsing logic in `NomisReport` to support the additional date format "dd/MM/yyyy HH:mm". Enhanced logging for validation errors and updated tests to ensure new formats and validation edge cases are covered comprehensively.

IR-1002 Update date parsing logic in NomisReport

---

src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/dto/nomis/NomisRequirement.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/jpa/Report.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/resource/NomisSyncResourceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/service/NomisSyncServiceTest.kt
src/test/resources/nomis-sync/sample-report.json

Refer 
- [hmpps-nomis-prisoner-api#1210](https://github.com/ministryofjustice/hmpps-nomis-prisoner-api/pull/1210)
- [hmpps-prisoner-from-nomis-migration#1448](https://github.com/ministryofjustice/hmpps-prisoner-from-nomis-migration/pull/1448)

IR-1094: Accept moment NOMIS’ requirement was recorded as a datetime

---

docs/0002-architecture.md

- Replaced Digital Prison Reporting (DPR) with Digital DataHub (DH) as the central source for reporting data.
- Updated names of components and interactions (e.g., Safety Diagnostic Tool (SDT), Performance Hub (PH), Analytics Platform).
- Adjusted data flow diagrams to include new components, like the Data Hub API, and clarified interactions between systems.
- Improved descriptions for several components, such as databases and APIs, for greater clarity.
- Incorporated changes to reflect bi-directional sync functionality (e.g., SYSCON services for incident data synchronization).

IR-1197 Revise architecture documentation for IRS
