- docs/0003-migration.md
The changes clarify the migration process from NOMIS to the new IRS, especially focusing on how new and existing incidents will be handled. The new strategy reflects updated procedures such as disabling the creation of new incidents in NOMIS and editing existing incidents in the new service. Additionally, it outlines how incident data will be treated in downstream systems and the eventual decommission of the NOMIS incident reporting service.
> IR-NONE Update migration strategy for incident reports from NOMIS to new IRS

- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/config/OpenApiConfiguration.kt
`securitySchemes` in OpenAPI output had a few issues…
1) `in` and `name` only apply to “apiKey” type (not the “http” that we use)
2) `openIdConnectUrl` only applies to “openIdConnect” type (not the “oauth2” that we use)
See https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.1.md#fixed-fields-23
[Copied from incentives-api](https://github.com/ministryofjustice/hmpps-incentives-api/pull/549/commits/9f943c4cadbb81a3d176c67a6157d511bfd555b1)
> IR-68: Copy OpenAPI fixes from incentives

- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/jpa/CorrectionRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/jpa/Event.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/jpa/Evidence.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/jpa/HistoricalQuestion.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/jpa/HistoricalResponse.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/jpa/History.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/jpa/Location.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/jpa/PrisonerInvolvement.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/jpa/Question.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/jpa/Report.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/jpa/Response.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/jpa/StaffInvolvement.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/jpa/StatusHistory.kt
We don't manually serialize JPA entities to files or over-the-wire and tests pass so these seems to be unnecessary.
(if in the future we find that these are required we can easily readd)
> Removed unnecessary `Serializable` marker interface from JPA entities

- src/test/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/dto/EntityToDtoMappingEdgeCaseTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/dto/NomisDtoToJpaMappingEdgeCaseTest.kt
Most mappings are already tested as part of end-to-end / integration resource and service tests (there are many JSON input / response assertions).
These extra test cases are for covering edge cases. And, potentially, for future additions of other edge cases.
> IR-199: Test NOMIS→Entity→DPS mappings

- src/main/resources/db/migration/V1_1__initial_schema.sql
The question `code` field was already expected to be non-null throughout the application.
NB: will require database resets when merging
> IR-68: Fix initial database setup

- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/dto/response/SimplePage.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/resource/ApiExceptionHandler.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/resource/ReportResource.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/service/ReportService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/resource/NomisSyncResourceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/resource/ReportResourceTest.kt
Filtering is not currently supported, but this will still be useful for periodic jobs to reconcile reports against NOMIS.
> IR-234: Add paginated endpoint to return all reports

- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/dto/nomis/Mapping.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/jpa/CorrectionRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/jpa/Event.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/jpa/Evidence.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/jpa/HistoricalQuestion.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/jpa/HistoricalResponse.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/jpa/History.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/jpa/Location.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/jpa/PrisonerInvolvement.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/jpa/Question.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/jpa/Report.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/jpa/Response.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/jpa/StaffInvolvement.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/jpa/StatusHistory.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/dto/NomisDtoToJpaMappingEdgeCaseTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/resource/NomisSyncResourceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/service/SyncServiceTest.kt
Report is now updated with information provided in sync request:
- type
- staff involvement
- prisoners involvement
- correction requests (called "requirements" in the NOMIS sync request)
- questions/answers
- history
Logic is very similar to one in Mapping. That's why I've extracted it into extension functions that they're reused in the (JPA) `Report`'s `updateWith()` method.
The main difference is that the `updateWith()` method _**clears**_ the associated records before adding whatever is provided by the sync request (using the `Mapping.kt` extensions function.
> IR-224: NOMIS sync endpoint updates report

- build.gradle.kts
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/jpa/Report.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/jpa/id/UuidV7Generator.kt
- src/main/resources/db/migration/V1_1__initial_schema.sql
…to have report primary keys be (almost certainly) lexicographically sequential. This will enable sorting reports in the database using the `id` column and retaining a stable order.
Note that:
• the current `org.hibernate.id.UUIDGenerator` is deprecated anyway
• and the suggested replacement `org.hibernate.id.uuid.UuidGenerator` only supports UUID v1 and v4
• deployed databases will need to be cleared prior to merging
> IR-236: Replace UUID generation with v7

- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/jpa/Event.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/jpa/HistoricalQuestion.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/jpa/History.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/jpa/Question.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/jpa/Report.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/resource/ReportResourceTest.kt
• missing `@OrderColumn` annotation on historical questions meant their order was not preserved
• missing `orphanRemoval = true` on some `@OneToMany` annotations meant that related entities remained in the database when they were explicitly removed
> IR-238: Ensure proper ordering and removal of related entities

- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/dto/nomis/Mapping.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/jpa/Report.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/jpa/repository/ReportRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/jpa/specifications/ReportSpecification.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/jpa/specifications/Specifications.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/resource/ReportResource.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/service/ReportService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/helper/IncidentReportBuilder.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/jpa/ReportRepositoryTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/resource/ReportResourceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/service/SyncServiceTest.kt
The initial endpoint returning reports did not permit filtering – it was intended to (slowly) serve _all_ reports for reconciliation page-by-page.
The endpoint becomes useful in a more general case now that filtering is possible by:
• prison
• information source
• report status
• incident type
• date range when the incident took place
• date range when the incident was reported
> IR-240: Filter reports by prison, source, status and type as well as when incidents took place or were reported 

- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/config/ApplicationInsightsConfiguration.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/jpa/Event.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/jpa/Report.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/resource/ApiExceptionHandler.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/resource/EventBaseResource.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/resource/ReportResource.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/service/AuditService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/service/EventPublishAndAuditService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/service/ReportService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/service/SnsService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/service/SyncService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/resource/ReportResourceTest.kt
NOMIS sync needs to be able to delete reports, but it makes sense to promote this facility to be general purpose. Even if the incident reporting user-facing service does not allow deleting reports, the incident report _api_ ought to provide the mechanism anyway (being a CRUD REST api).
Now:
• reports can be deleted by primary key
• write scope is needed, but currently, only the regular `MAINTAIN_INCIDENT_REPORTS` role is required
• deletion is logged and a domain event is raised
• orphaned events are deleted by default
> IR-242: Add deletion endpoint

- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/jpa/HistoricalQuestion.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/jpa/History.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/jpa/Question.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/jpa/Report.kt
- src/main/resources/db/migration/V1_1__initial_schema.sql
Selectively annotating some related entities to load eagerly, can slightly improve performance (though it remains poor).
This _appears_ to cut the number of SQL queries quite a bit for the report retrieving (both one and many).
> IR-247: Eager-load related entities from `Report`

- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/service/SubjectAccessRequestService.kt
Previously, the order wasn’t stable and filtering was based on when the report was created (arguably a less interesting moment)
> IR-257: Return reports for SAR endpoint in stable order by incident date

- .circleci/config.yml
Ref [hmpps-template-kotlin#209](https://github.com/ministryofjustice/hmpps-template-kotlin/pull/209)
> IR-68: Use same version of java for Veracode scanning as required by HMPPS plugins

- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/service/PrisonOffenderEventListener.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/integration/SqsIntegrationTestBase.kt
- src/test/resources/application-test.yml
We are currently subscribed to these domain events but we didn't do anything with them.
This means messages accumulate in the queue and we're getting some alerts.
This should stop these alerts from happening.
PS: We will eventually have to introduce some logic to handle the merge of two prisoner numbers (e.g. updating prisoner involvement) but that's for another day.
> IR-256: Listen to (but ignore) 'prisoner.merged' events

- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/jpa/Report.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/jpa/id/UuidV7Generator.kt
…because `org.hibernate.annotations.GenericGenerator` is deprecated as of hibernate 6.5 and the suggested alternative is to make a `@IdGeneratorType` annotation.
> IR-68: Create annotation for generation of UUID v7 values

- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/dto/response/NomisSyncReportId.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/resource/NomisSyncResource.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/resource/NomisSyncResourceTest.kt
…instead of a string. I.e.:
Was:
```json
"019001e5-0233-75ce-afa3-1113d7dc7ec3"
```
Now:
```json
{"id": "019001e5-0233-75ce-afa3-1113d7dc7ec3"}
```
> IR-269: Return incident report ID as an object from NOMIS sync resource

- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/jpa/repository/ReportRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/resource/ReportResource.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/service/ReportService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/config/JwtAuthHelper.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/dto/EntityToDtoMappingEdgeCaseTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/dto/NomisDtoToJpaMappingEdgeCaseTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/integration/SqsIntegrationTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/jpa/ReportRepositoryTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/resource/ConstantsResourceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/resource/NomisSyncResourceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/resource/ReportResourceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/service/NomisSyncServiceTest.kt
It would have taken less code to have responses switch based on a request parameter, but the OpenAPI schema is probably cleaner without using an `oneOf` return type.
> IR-273: Allow clients to choose between basic and with-details responses in single report endpoints

- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/dto/request/ChangeStatusRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/dto/request/ChangeTypeRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/dto/utils/MaybeChanged.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/jpa/Report.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/resource/ApiExceptionHandler.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/resource/NomisSyncResource.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/resource/ReportResource.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/service/ReportService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/dto/MaybeChangedTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/resource/ReportResourceTest.kt
Changing a report’s status or type has a side effect of preserving the history, so there are now separate endpoints from the generic PATCH report method.
Changing a type to an inactive one is not allowed.
We still do not know what the lifecycle of a report is so there is no restriction on what transitions are allowed for status. Should the api permit any status change? Should it instead check the user’s role and disallow some? For instance, perhaps only QAs or central support can re-open a report once it has been closed.
> IR-281 & IR-282: Allow changing a report’s status or type

- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/resource/EventBaseResource.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/resource/NomisSyncResource.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/resource/ReportCorrectionRequestResource.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/resource/ReportEvidenceResource.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/resource/ReportLocationResource.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/resource/ReportPrisonerInvolvementResource.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/resource/ReportRelatedObjectsResource.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/resource/ReportResource.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/resource/ReportStaffInvolvementResource.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/service/EventPublishAndAuditService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/service/SnsService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/integration/SqsIntegrationTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/resource/NomisSyncResourceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/resource/ReportResourceTest.kt
When a Report is updated the published `incident.report.amended` has a `whatChanged` field in the `additionalInformation`.
This field is an enum that the consumers of these domain events can use to have a better idea of what part of the report changed, e.g. prisoners involved, staff involved, etc...
If the endpoint to update only the basic information ([`PATCH /incident-reports/{id}`](https://incident-reporting-api-dev.hmpps.service.justice.gov.uk/swagger-ui/index.html#/Incident%20reports/updateReport)) was used this field would be set to `BASIC_REPORT` to indicate that only the Report key properties may have changed.
The sync upsert endpoint is a bit special in the sense that the client pass the whole Report's blob.
This means that any part of the Report could change (and potentially …
> IRS-291: Domain events include an hint of what part of the report changed

- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/dto/request/AddQuestionWithResponses.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/dto/request/CreateReportRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/jpa/Question.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/jpa/Report.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/resource/ReportQuestionResponseResource.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/service/ReportService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/service/SnsService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/resource/ReportResourceTest.kt
- src/test/resources/questions-with-responses/add-request-empty-question.json
- src/test/resources/questions-with-responses/add-request-empty-response.json
- src/test/resources/questions-with-responses/add-request-long-code.json
- src/test/resources/questions-with-responses/add-request-short-staff-username.json
- src/test/resources/questions-with-responses/add-request-with-responses-and-null-fields.json
- src/test/resources/questions-with-responses/add-request-with-responses.json
- src/test/resources/questions-with-responses/add-request-without-responses.json
- src/test/resources/questions-with-responses/add-response-with-responses-and-null-fields.json
- src/test/resources/questions-with-responses/add-response-with-responses.json
- src/test/resources/questions-with-responses/add-response-without-responses.json
- src/test/resources/questions-with-responses/delete-response.json
- src/test/resources/questions-with-responses/list-response-with-several.json
- Questions are always listed in order of insertion
- …their responses are always listed in order of insertion
- Question and response IDs are not exposed
- A question can be added to a report if it has at least one response
- The last question (and all of its responses) can be deleted if it exists
- Because subsequent questions often depend on prior responses, you cannot modify any existing questions nor delete any but the last one
- Should there be a need to modify something in the middle, it and all subsequent questions should be deleted and recreated as needed
---
> IR-292: CRUD API endpoints for questions and responses

- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/dto/request/AddCorrectionRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/dto/request/AddEvidence.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/dto/request/AddLocation.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/dto/request/AddPrisonerInvolvement.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/dto/request/AddQuestionWithResponses.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/dto/request/AddStaffInvolvement.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/dto/request/CreateReportRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/dto/request/UpdateCorrectionRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/dto/request/UpdateEvidence.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/dto/request/UpdateLocation.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/dto/request/UpdatePrisonerInvolvement.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/dto/request/UpdateReportRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/dto/request/UpdateStaffInvolvement.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/resource/ReportResource.kt
NB: Nullable comment-type fields allow empty strings
> IR-68: Tighten string length validation and in swagger/open-api documentation

- docs/0004-modeling-irs.md
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/config/ApplicationInsightsConfiguration.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/dto/Event.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/dto/ReportBasic.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/dto/ReportWithDetails.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/dto/nomis/Mapping.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/dto/request/CreateReportRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/jpa/Event.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/jpa/Report.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/jpa/repository/EventRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/jpa/repository/ReportRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/resource/EventBaseResource.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/resource/ReportRelatedObjectsResource.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/resource/ReportResource.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/service/NomisSyncService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/service/ReportService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/service/SnsService.kt
- src/main/resources/db/migration/V1_1__initial_schema.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/dto/EntityToDtoMappingEdgeCaseTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/dto/NomisDtoToJpaMappingEdgeCaseTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/helper/IncidentReportBuilder.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/integration/SqsIntegrationTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/jpa/ReportRepositoryTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/resource/NomisSyncResourceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/resource/ReportResourceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/service/NomisSyncServiceTest.kt
- src/test/resources/entity-mapping/sample-report-basic.json
- src/test/resources/entity-mapping/sample-report-with-details.json
1. To make the human-visible identifiers consistent, it’d be good to name them similarly.
2. Human-visible identifier for Event sounds an awful lot like its primary key – both were basically “event ID“
`Event.eventId` → `Event.eventReference`
`Report.incidentNumber` → `Report.reportReference`
TODO:
- **drop all deployed databases before merging!**
- [update HMPPS domain events docs](https://github.com/ministryofjustice/hmpps-domain-events/pull/38)
- [update NOMIS migration/reconciliation](https://github.com/ministryofjustice/hmpps-prisoner-from-nomis-migration/pull/720)
> IR-385: Rename the human-visible identifier of events and reports

- docs/0004-modeling-irs.md
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/jpa/Event.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/jpa/repository/EventRepository.kt
- src/main/resources/db/migration/V1_1__initial_schema.sql
This is for consistency with the Report model/table and it can aid against URL-browsing to other events as IDs are now difficult to predict.
> IR-383: Event uses UUID as primary key, not longs

- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/jpa/Event.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/jpa/Report.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/service/PrisonOffenderEventListener.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/service/ReportService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/service/PrisonerMergeTest.kt
…by replacing given prisoner number in all involvement entities.
Open question remains: if reports and events will have auto-generated titles, and if prisoner numbers are included, we should rename these too
> IR-395: React to HMPPS prisoner merge domain event

- docs/0004-modeling-irs.md
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/dto/HistoricalResponse.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/dto/Response.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/dto/nomis/Mapping.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/dto/nomis/NomisHistoryResponse.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/dto/nomis/NomisResponse.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/dto/request/AddQuestionWithResponses.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/jpa/HistoricalQuestion.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/jpa/HistoricalResponse.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/jpa/Question.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/jpa/Report.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/jpa/Response.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/service/ReportService.kt
- src/main/resources/db/migration/V1_1__initial_schema.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/helper/ReportBuilder.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/jpa/ReportRepositoryTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/resource/NomisSyncResourceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/resource/ReportResourceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/service/NomisSyncServiceTest.kt
- src/test/resources/entity-mapping/sample-report-with-details.json
- src/test/resources/questions-with-responses/add-request-empty-question.json
- src/test/resources/questions-with-responses/add-request-empty-response.json
- src/test/resources/questions-with-responses/add-request-with-responses-and-null-fields.json
- src/test/resources/questions-with-responses/add-request-with-responses.json
- src/test/resources/questions-with-responses/add-response-with-responses-and-null-fields.json
- src/test/resources/questions-with-responses/add-response-with-responses.json
- src/test/resources/questions-with-responses/add-response-without-responses.json
- src/test/resources/questions-with-responses/delete-response.json
- src/test/resources/questions-with-responses/list-response-with-several.json
In NOMIS, some responses ask the user to enter a date alongside. This was missed and previously only the comment / additional information field was being handled.
In future, the DPS version of incident reporting may or may not ask users to enter dates, but historic information needs to still be preserved.
*NB: Will require databases to be trashed when deploying*
> IR-401: Add date field to responses

- src/main/resources/db/migration/V1_2__add_fks_indexes.sql
`dev` environment was very slow, after investigation I realised tables didn't have indexes on Foreign Keys (FK) columns.
Manually add these indexes resolved these performances issues. (I imagine the bulk of the problem was caused by the ~10M records in the `question`/`response` DB tables)
This PR properly add these indexes (so that they're also added to `preprod`/`prod`)
> IR-402: Added indexes on FKs columns

- Dockerfile
…since gradle now complains about not finding the right toolchain
> IR-68: Build application using JDK (not JRE) base image

- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/constants/Type.kt
NOMIS has now got 3 drone sightings types: DRONE (inactive and used in the past), DRONE1 (active and in use) and DRONE2 (active and in use)
> IR-405: Add new `DRONE2` report type

- src/main/resources/db/migration/V1_4__increase_report_sequence.sql
Previously this was 1,000,000 but this is too low.
There are ~2 million reports. Recent report's reference numbers are already in the ~4.5 millions.
Starting at 1,000,000 can lead to clashes with NOMIS reference numbers.
> IR-381: Increase report sequence to 10,000,000

- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/jpa/Event.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/jpa/Report.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/jpa/repository/EventRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/jpa/repository/ReportRepository.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/dto/EntityToDtoMappingEdgeCaseTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/helper/ReportBuilder.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/jpa/EventRepositoryTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/jpa/ReportRepositoryTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/resource/EventResourceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/resource/ReportResourceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/service/PrisonerMergeTest.kt
- src/test/resources/entity-mapping/sample-report-basic.json
- src/test/resources/entity-mapping/sample-report-with-details.json
The references are still a string but it doesn't have the `IE-`/`IR-` prefixes and also lost the leading 0s (as these would likely be ignored when searching and they'd lead to confusion when no event/report would match).
Bearing in mind our sequences start at 10,000,000 which means new DPS events/reports would have a reference which is at least `'10000000'` (while old NOMIS references would be lower as expected)
> IR-381: Remove IE-/IR- prefix from event/report references

- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
Use `alertSeverity` provided by CP team.
These would send alerts to the `#incident-reporting-service-dev` Slack channel.
> IR-421: Send alerts to our dev channel

- docker-compose-local.yml
Use the same docker image tags and container names as UI app’s docker compose setup.
See also [ui#158](https://github.com/ministryofjustice/hmpps-incident-reporting/pull/158)
> IR-431: Local setup

- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/constants/PrisonerRole.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/dto/response/PrisonerRoleConstantDescription.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/resource/ConstantsResource.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/resource/ConstantsResourceTest.kt
These codes can be used by the UI to map between an old `PrisonerInvolvemtRole` and a new `PrisonerInvolvemtRole`.
> Expose `nomisCode` in PrisonerRole constants endpoint

- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/dto/request/NomisSyncRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/resource/NomisSyncResource.kt
This is to make auto-generated code in `hmpps-prisoner-from-nomis-migration` simpler to use.
> IR-68: Expose polymorphic base type in swagger docs for sync payloads from NOMIS

- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/service/PrisonOffenderEventListener.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/service/ReportService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/integration/IntegrationTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/service/PrisonerMergeTest.kt
… when reacting to an event indicating that a booking was moved between two prisoner numbers. Previously, we incorrectly moved _all_ references to the moved prisoner number (not just that one booking).
This is now possible because the [`prison-offender-events.prisoner.booking.moved` domain event](https://studio.asyncapi.com/?url=https://raw.githubusercontent.com/ministryofjustice/prison-offender-events/main/async-api.yml&readOnly#message-prison-offender-events.prisoner.booking.moved) includes the booking start date.
> IR-562: Only replace prisoner numbers reported within a booking’s date range

- helm_deploy/hmpps-incident-reporting-api/values.yaml
…the k8s secret itself is created by terraform from a shared DPS secret in a AWS systems manager parameter
Ref: [hmpps-template-kotlin#254](https://github.com/ministryofjustice/hmpps-template-kotlin/pull/254)
> IR-68: Get Azure Application Insights settings from kubernetes secret directly

- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/dto/HistoricalQuestion.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/dto/HistoricalResponse.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/dto/Question.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/dto/Response.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/dto/request/AddOrUpdateQuestionWithResponses.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/jpa/HistoricalQuestion.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/jpa/HistoricalResponse.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/jpa/Question.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/jpa/Response.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/resource/ReportQuestionResponseResource.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/service/ReportService.kt
- src/main/resources/db/migration/V1_4__question_codes.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/resource/ReportResourceTest.kt
- src/test/resources/questions-with-responses/add-and-update-request-with-responses.json
- src/test/resources/questions-with-responses/add-and-update-response-with-responses.json
- src/test/resources/questions-with-responses/update-request-with-responses.json
- src/test/resources/questions-with-responses/update-response-with-responses.json
…so that:
1) questions can be updated in place (replacing all responses with new ones)
2) questions can be referenced directly and stably by the UI app
`/incident-reports/{reportId}/questions` endpoint now only accepts PUT requests and returns 200 CREATED.
New table constraints will take a long time to apply so should be run manually followed by
```sql
insert into flyway_schema_history (installed_rank, version, description, type, script, checksum, installed_by, installed_on, execution_time, success)
values (4, '1.4', 'question codes', 'SQL', 'V1_4__question_codes.sql', -1754573454, 'incident_reporting', now(), 0, true);
```
> IR-686: Make question `code` field a unique identifier for questions within individual reports

- src/main/resources/db/migration/V1_5__question_code_index.sql
Improves performance of changes in #220
NB: indices already created in all databases because it takes 120s+ and must be run manually. hence `if not exists` in the migration script.
> IR-696: Add database indices to speed up referencing questions by code

- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/service/PrisonOffenderEventListener.kt
- src/main/resources/application.yml
The “booking moved” one erroneously included “merge” in it's name and they both might as well be spelled out more clearly
> IR-68: Rename domain event data classes to be a bit clearer

- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/constants/PrisonerOutcome.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/constants/PrisonerRole.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/constants/StaffRole.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/constants/Status.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/constants/Type.kt
- src/main/resources/db/migration/V1_14__constants.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/jpa/ConstantsTableTest.kt
…for use only in reporting; Analytical Platform & DPR.
The application will continue to only use all values solely from internal constants in `uk.gov.justice.digital.hmpps.incidentreporting.constants`.
NB:
- any changes to constants / enumeration classes _require_ new migrations!
- these tables should NOT be used in foreign key constraints! otherwise migrations would be overly-complicated
- NOMIS codes are not included because DPR reports are being recreated and there’s no need to preserve a link to data that will be removed
> IR-771: Copy constant enumerations in to database tables

- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/jpa/Report.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/jpa/ReportRepositoryTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/resource/ReportResourceTest.kt
If a report’s type is changed, prisoner involvement roles could become invalid – all are now cleared.
API does not enforce rules around statuses, client applications should only change type when it is appropriate.
> IR-954: Handle side effects of changing a report’s type

- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/jpa/specifications/ReportSpecification.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/resource/ReportResource.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/service/ReportService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/jpa/ReportRepositoryTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/resource/ReportResourceTest.kt
Apparently we could only filter by one at a time before; I forgot that
> Allow filtering list of basic reports by more than one incident type

- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/dto/DescriptionAddendum.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/dto/ReportWithDetails.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/jpa/DescriptionAddendum.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/jpa/Report.kt
- src/main/resources/db/migration/V1_19__add_description_addendum.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/helper/ReportBuilder.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/jpa/ReportRepositoryTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/resource/NomisSyncResourceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/resource/ReportResourceTest.kt
- a report can have many description addendums (text appended to the description by a user)
- added `description_addendum` table to contain these records
- endpoints returning a `ReportWithDetails` response will include these description addendums (while basic report will not as they don't include these kind of related objects, for performance reasons)
- this should not be a breaking change
NOTE: This is the foundation for other parts of this work, e.g. an endpoint to create these description addendums, but these will be part of separate PRs.
> IR-887: Description addendums (data model)

- helm_deploy/hmpps-incident-reporting-api/templates/refresh-views-cronjob.yaml
This Pull Request (PR) updates the configuration for the refresh-views-cronjob in the hmpps-incident-reporting-api Helm deployment template. The changes introduce environment-specific conditions and modify the cronjob schedule for non-production environments.
- Added conditional logic to include the cronjob definition only for environments prod and dev.
- Adjusted the schedule for non-production environments to run at 19:00 instead of 20:00.
- Ensured the cronjob definition is enclosed within the new conditional block to avoid unnecessary deployment in other environments.
> IR-1008 Update refresh-views-cronjob.yaml to adjust non-production schedule to 19:00 and exclude pre-prod

- helm_deploy/values-prod.yaml
```
This pull request introduces an environment variable `SCHEMA_TO_RESTORE` to control schema restoration during database recovery. Specifically, the updates enable only the `public` schema to be restored while excluding the `report` schema.
```
> IR-1068 Add SCHEMA_TO_RESTORE variable for selective database restoration

- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/dto/nomis/NomisRequirement.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/jpa/Report.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/resource/NomisSyncResourceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/service/NomisSyncServiceTest.kt
- src/test/resources/nomis-sync/sample-report.json
#342 and NOMIS side have been deployed in all environments so can proceed…
Refer:
- [hmpps-nomis-prisoner-api#1214](https://github.com/ministryofjustice/hmpps-nomis-prisoner-api/pull/1214)
- [hmpps-prisoner-from-nomis-migration#1450](https://github.com/ministryofjustice/hmpps-prisoner-from-nomis-migration/pull/1450)
> IR-1094: Accept moment NOMIS’ requirement was recorded as a datetime using new field only

- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/dto/HistoricalResponse.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/dto/Response.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/dto/request/AddOrUpdateQuestionWithResponses.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/jpa/HistoricalQuestion.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/jpa/HistoricalResponse.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/jpa/Question.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/jpa/Report.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/jpa/Response.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/service/ReportService.kt
- src/main/resources/db/migration/V1_23__add_code_column_to_responses.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/helper/ReportBuilder.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/jpa/ReportRepositoryTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/resource/DprReportingIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/resource/NomisSyncResourceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/resource/ReportResourceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/service/NomisSyncServiceTest.kt
- src/test/resources/questions-with-responses/add-and-update-request-with-responses.json
- src/test/resources/questions-with-responses/add-and-update-response-with-responses.json
- src/test/resources/questions-with-responses/add-response-3-questions-with-responses.json
- src/test/resources/questions-with-responses/add-response-with-responses-and-null-fields.json
- src/test/resources/questions-with-responses/add-response-with-responses.json
- src/test/resources/questions-with-responses/add-response-without-responses.json
- src/test/resources/questions-with-responses/delete-response.json
- src/test/resources/questions-with-responses/update-request-with-responses-with-codes.json
- src/test/resources/questions-with-responses/update-response-with-responses-with-codes.json
- src/test/resources/questions-with-responses/update-response-with-responses.json
This Pull Request introduces a new code field to various response-related models, both in the API layer (DTOs) and the database schema. The code field serves as a unique identifier for responses, enabling better traceability and uniqueness. Changes are also accompanied by updates to tests, JSON payloads, and database migrations.
- New Field Addition:
- Added code as an optional field in the HistoricalResponse, Response, and related models.
- Updated constructors and methods across models to incorporate the new code field.
- Database Updates:
- Added a new code column to the response and historical_response tables via SQL migration.
- Indexed the code column for performance when used with question_id.
- Logic Updates:
- Modified methods to handle the new code field for inserting/updating …
> IR-1098 Add `code` field to responses.

- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/dto/request/AddOrUpdateQuestionWithResponses.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/jpa/HistoricalQuestion.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/jpa/HistoricalResponse.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/jpa/Question.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/jpa/Response.kt
- src/main/resources/db/migration/V1_25__make_response_code_not_null.sql
- src/test/resources/questions-with-responses/add-and-update-request-with-responses.json
- src/test/resources/questions-with-responses/add-and-update-response-with-responses.json
- src/test/resources/questions-with-responses/add-request-3-questions-with-responses.json
- src/test/resources/questions-with-responses/add-request-empty-question.json
- src/test/resources/questions-with-responses/add-request-empty-response.json
- src/test/resources/questions-with-responses/add-request-long-code.json
- src/test/resources/questions-with-responses/add-request-with-responses-and-null-fields.json
- src/test/resources/questions-with-responses/add-request-with-responses.json
- src/test/resources/questions-with-responses/add-response-3-questions-with-responses.json
- src/test/resources/questions-with-responses/add-response-with-responses-and-null-fields.json
- src/test/resources/questions-with-responses/add-response-with-responses.json
- src/test/resources/questions-with-responses/add-response-without-responses.json
- src/test/resources/questions-with-responses/update-request-with-responses.json
- src/test/resources/questions-with-responses/update-response-with-responses.json
- Made the code field non-null in multiple data classes (AddOrUpdateQuestionResponse, HistoricalQuestion, HistoricalResponse, Question, and Response) to enforce mandatory values.
- Updated related methods (addResponse) to align with the non-null constraint for code.
- Added a database migration script to set the code field as NOT NULL in the response and historical_response tables.
- Updated test data JSON files to include non-null code fields where applicable.
> IR-1115 Make `code` field mandatory for responses. (#367)

- helm_deploy/hmpps-incident-reporting-api/values.yaml
Since yesterday afternoon we're seeing a lot of errors in `dev` and pods restarts.
Pods logs have a bunch of errors like:
`java.lang.OutOfMemoryError: Java heap space`
While the RDS instance resource usage seems to be fine, but the logs also have a bunch of errors along the line of `connection reset by peer`, again, pointing in the direction of the API pods rather than a problem with the DB sizing (AFAICT).
Production memory was already [tweaked in March] possibly because of a similar problem, so I'm updating the
memory across all the environments, specifically the Java maximum heap memory allocation.
[tweaked in March]: https://github.com/ministryofjustice/hmpps-incident-reporting-api/commit/d059c3e8126d38661e1c21d241142b1750f54673
> Increased memory across all the environments

- helm_deploy/hmpps-incident-reporting-api/values.yaml
We have increased the Java max memory heap allocation but the k8s pods seem to have a memory limit of
1GB even tho we haven't set that anywhere:
```YAML
resources:
limits:
cpu: "2"
memory: 1Gi
requests:
cpu: 10m
memory: 512Mi
```
This would be hit by the application before the
3GB Java limit, so I'm bumping this to match that.
> Increase k8s pod memory limit

- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/constants/Status.kt
- src/main/resources/db/migration/V1_31__delete_post_incident_update_status.sql
…it’s now gone from NOMIS in all environments
> IR-1040: Remove “Post-incident update” status

- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/constants/Status.kt
- src/main/resources/db/migration/V1_32__undelete_post_incident_update_status.sql
Reverts ministryofjustice/hmpps-incident-reporting-api#376
> Undo IR-1040: Remove “Post-incident update” status

- renovate.json
- ~wait 3 days before using a new version of a dependency~
- bump `swagger-parser` separately
- bump DPR library separately
> Renovate tweaks

- docs/0004-modeling-irs.md
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/constants/Status.kt
- src/main/resources/db/migration/V1_33__correctly_delete_post_incident_update_status.sql
`PIU` had in fact been deactivated in NOMIS correctly, but remained in the status history table here – such reports could no longer be deserialised from the database correctly.
> IR-1040: Re-remove “Post-incident update” status

- renovate.json
Renovate considers the whole path of package as
package name, e.g. for a package called `org.springframework.boot:spring-boot-starter-web` `matchPackageNames` would have to be the whole `group:name`, so
```
"matchPackageNames": ["org.springframework.boot:spring-boot-starter-web"]
```
Or use regular expressions.
> Fix `matchPackageNames` matches

- renovate.json
Renovates applies the first matching `packageRule` or so I thought, but apparently when more than one rule matches the last rule wins - so it's the opposite of what I thought: More specific rules should come after.
> Attempt to fix renovate rules order

- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/constants/Status.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/dto/response/StatusConstantDescription.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/resource/ConstantsResource.kt
- src/main/resources/db/migration/V1_34__statuses_ignored_downstream.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/resource/ConstantsResourceTest.kt
…so that other services can know which report statuses should be ignored for most statistical purposes
> Add `ignore_downstream` flag to status constants table

- helm_deploy/hmpps-incident-reporting-api/values.yaml
- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/service/PrisonOffenderEventListener.kt
This Pull Request updates the configuration files for various environments and modifies the PrisonOffenderEventListener class by removing unnecessary imports and improving log messages.
Added -XX:+HeapDumpOnOutOfMemoryError option to JAVA_OPTS across multiple environment-specific YAML files.
Adjusted memory limits in some environments.
Removed OpenTelemetry-related imports (SpanKind and WithSpan) from PrisonOffenderEventListener.
Improved log message structure for message reception and processing in PrisonOffenderEventListener.
> IR-1171 Dump out Heap space

- helm_deploy/hmpps-incident-reporting-api/values.yaml
- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- src/main/kotlin/uk/gov/justice/digital/hmpps/incidentreporting/jpa/Report.kt
- Removed `historyOfStatuses` attribute from eager fetching in the `Report` subgraph to address Cartesian join memory issues.
- Cleaned up memory-related configurations for better consistency.
- Standardized `JAVA_OPTS` across all Helm values files.
> IR-1171 Remove memory-intensive eager fetching and standardize configurations
